function trial = MotoTrak_Update_Trial_Plots(handles,session,trial)

%
%MotoTrak_Update_Trial_Plots.m - Vulintus, Inc.
%
%   MOTOTRAK_UPDATE_TRIAL_PLOTS plots new streaming data from the MotoTrak
%   controller to the streaming plots on the MotoTrak GUI during a trial.
%   
%   UPDATE LOG:
%   05/02/2015 - Drew Sloan - Function first implemented, cutting existing
%       trial signal plotting sections from MotoTrak_Behavior_Loop.m.
%


cur_tab = handles.plot_tab_grp.SelectedTab.Title;                           %Grab the currently selected tab title.
if strcmpi(handles.device,'both')                                           %If this is a combined touch-pull session...
        set(trial.plot_h(1),'ydata',session.buffer(:,2));                   %Update the force area plot.
    trial.max_y = ...
        [min([1.1*min(session.buffer(:,2)), -0.1*trial.thresh]),...
        max([1.1*max(session.buffer(:,2)), 1.3*trial.thresh])];             %Calculate new y-axis limits.
    ylim(handles.primary_ax,trial.max_y);                                   %Set the new y-axis limits.
    set(trial.plot_h(3),'ydata',trial.mon_signal);                          %Update the touch area plot.
    trial.max_y = ...
        [min([1.1*min(trial.mon_signal), -1.1*handles.init]),...
        max([1.1*max(trial.mon_signal), 1.1*handles.init])];                %Calculate new y-axis limits.
    ylim(handles.secondary_ax,trial.max_y);                                 %Set the new y-axis limits.
else                                                                        %Otherwise...
    switch lower(cur_tab)                                                   %Switch between the tabs...
        case {'supination angle',...
                'pull force',...
                'lever angle'}                                              %If the selected tab is the primary signal...    
            set(trial.plot_h(1),'ydata',trial.signal);                      %Update the area plot.
            if strcmpi(handles.curthreshtype,'# of spins') ...
                    || strcmpi(handles.curthreshtype,'presses')
                set(trial.plot_h(2),'xdata',trial.peak_indices-1,...
                    'ydata',trial.peak_vals);                               %Update the peak markers.
                for i = 1:length(trial.peak_vals)                           %Step through each of the peaks.
                    x = trial.peak_indices(i) - 1;                          %Calculate x coordinates for a peak label.
                    y = trial.peak_vals(i);                                 %Calculate y coordinates for a peak label.
                    if i > length(trial.peak_text)                          %If this is a new peak since the last data read...
                        str = num2str(i);                                   %Convert the peak index to a string.
                        trial.peak_text(i) = text(x,y,str,...
                            'horizontalalignment','left',...
                            'verticalalignment','bottom',...
                            'fontsize',8,...
                            'fontweight','bold',...
                            'parent',handles.primary_ax);                   %Create text to mark each peak in the hit window.
                    else                                                    %Otherwise, if this isn't a new peak...
                        set(trial.peak_text(i),'position',[x,y]);           %Update the position of the peak label.
                    end
                end
            end
            if ~isnan(handles.ceiling) && handles.ceiling ~= Inf            %If a ceiling is set for this stage...
                trial.max_y = [min([1.1*min(trial.signal),...
                    -0.1*handles.ceiling]),...
                    max([1.3*max(trial.signal), 1.3*handles.ceiling])];     %Calculate new y-axis limits.
            else                                                            %Otherwise, if there is no ceiling set for this stage...
                trial.max_y = [min([1.1*min(trial.signal),...
                    -0.1*trial.thresh]),...
                    max([1.3*max(trial.signal), 1.3*trial.thresh])];        %Calculate new y-axis limits.
            end
            set(trial.trial_txt,'position',[1,trial.max_y(2)]);             %Update the text postiion.
            ylim(handles.primary_ax,trial.max_y);                           %Set the new y-axis limits.            
            set(trial.ln,'ydata',trial.max_y);                              %Update the lines marking the hit window bounds.
        case 'swipe sensor'                                                 %If the selected tab is the secondary signal...
            set(trial.plot_h(3),'ydata',session.buffer(:,3),...
                'basevalue',session.minmax_ir(1));                          %Update the IR signal plot.
            set(trial.ir_thresh_ln,'ydata',[1,1]*session.minmax_ir(3));     %Update the threshold line.
            set(trial.ir_thresh_txt,'position',[1,session.minmax_ir(3)]);   %Update the threshold line label.
            temp = session.minmax_ir(1:2);                                  %Grab the current historical minimum and maximum.
            if temp(1) > temp(2)                                            %If the 1st value is greater than the second...
                temp = [0, 1023];                                           %Set the infrared bounds to the maximum possible.
            elseif temp(1) == temp(2)                                       %If the 1st value equals the 2nd...
                temp = temp(1) + [-1,1];                                    %Add one above and below the single value.
            end
            temp = temp + [-0.1,0.1]*(temp(2) - temp(1));                   %Calculate y-axis limits.
            ylim(handles.secondary_ax,temp);                                %Set the secondary axes y-axis limits.
    end
end