function device = MotoTrak_Identify_Device(val)

if val < 20                                                                 %If the device-identifier value is less than ~0.1V...
    device = 'none';                                                        %There is no device connected.
elseif val >= 20 && val < 100                                               %If the device-identifier value is between ~0.1V and ~0.5V...
    device = 'lever';                                                       %The device is the lever (1.5 MOhm resistor).
elseif val >= 100 && val < 200                                              %If the device-identifier value is between ~0.5V and ~1.0V...
    device = 'knob';                                                        %The device is the knob (560 kOhm resistor).
elseif val >= 200 && val < 300                                              %If the device-identifier value is between ~1.0V and ~1.5V...
    device = 'knob';                                                        %The device is the knob (270 kOhm resistor).
elseif val >= 300 && val < 400                                              %If the device-identifier value is between ~1.5V and ~2.0V...
    device = 'knob';                                                        %The device is the knob (200 kOhm resistor).
elseif val >= 400 && val < 500                                              %If the device-identifier value is between ~2.0V and ~2.5V...
    device = 'pull';                                                        %The device is the pull (130 kOhm resistor).
elseif val >= 500 && val < 600                                              %If the device-identifier value is between ~2.5V and ~3.0V...
    device = 'pull';                                                        %The device is the pull (85 kOhm resistor).
elseif val >= 600 && val < 700                                              %If the device-identifier value is between ~3.0V and ~3.5V...
    device = 'pull';                                                        %The device is the pull (57 kOhm resistor).
elseif val >= 700 && val < 800                                              %If the device-identifier value is between ~3.5V and ~4.0V...
    device = 'pull';                                                        %The device is the pull (36 kOhm resistor).
elseif val >= 800 && val < 900                                              %If the device-identifier value is between ~4.0V and ~4.5V...
    device = 'lever';                                                       %The device is the lever (20 kOhm resistor).
elseif val >= 900 && val < 1000                                             %If the device-identifier value is between ~4.5V and ~5.0V...
    device = 'knob';                                                        %The device is the knob (8 kOhm resistor).
elseif val >= 1000                                                          %If the device-identifier value is greather than ~5.0V...
    device = 'knob';                                                        %The device is the knob (wire jumper).
end